### ISSUE TITLE
DUMP_PATH

### ISSUE THREAD

**Issue by zhenzhang1998** [LUSSeg/PASS#3]
run `bash scripts/luss50_pass_jt.sh`, report no file , what the means of `DUMP_PATH` in `luss50_pass_jt.sh`

![image](https://github.com/LUSSeg/PASS/assets/131339099/ddedeebf-72a0-46ee-9e10-0c52ffd50bff)

![image](https://github.com/LUSSeg/PASS/assets/131339099/5adf2e47-11f9-4fd1-8d9f-14f8f6feb4bc)

**Comment by TousenKaname** [comment]
Do you solve the problem?I had the same problem.Thanks~!
