### ISSUE TITLE
run `luss50_pass_jt.sh` compile error

### ISSUE THREAD

**Issue by zhenzhang1998** [LUSSeg/PASS#4]
![image](https://github.com/LUSSeg/PASS/assets/131339099/d883408f-5250-4e16-979f-a2572cc47ef2)

![image](https://github.com/LUSSeg/PASS/assets/131339099/04f64a9d-654d-4165-942d-eea0e7f67dfa)

**Comment by zhenzhang1998** [comment]
查找后，我发现 `python -m jittor.test.test_array` 无法通过，找不到`libgcc_s.so.1`, 然后我用`ctypes.CDLL('libgcc_s.so.1')`导入，还是有错误，感觉可能是array相关的问题

这是 test_array的报错信息
![image](https://github.com/LUSSeg/PASS/assets/131339099/9f951bc1-95e7-46d6-9e0e-c71f249411a8)

**Comment by lzyhha** [comment]
It seems an issue about jitter compiling. Can you help to solve that? @uyzhang

**Comment by uyzhang** [comment]
> It seems an issue about jitter compiling. Can you help to solve that? @uyzhang

This issue has been resolved in the QQ group.

**Comment by lzyhha** [comment]
这是来自QQ邮箱的自动回复邮件。This is a automatic response.

**Comment by TousenKaname** [comment]
Could you tell the QQ group number? Thanks!

**Comment by lzyhha** [comment]
这是来自QQ邮箱的自动回复邮件。This is a automatic response.

**Comment by uyzhang** [comment]
> Could you tell the QQ group number? Thanks!

1018591346

**Comment by TousenKaname** [comment]
你好，请问您跑代码所用的版本号是什么呢？我跑代码然后停在这里没有反应您知道什么情况吗？
![image](https://github.com/LUSSeg/PASS/assets/55678087/57cae1bd-1d52-4730-a9e1-6d4458b39860)

**Comment by uyzhang** [comment]
> 你好，请问您跑代码所用的版本号是什么呢？我跑代码然后停在这里没有反应您知道什么情况吗？ ![image](https://user-images.githubusercontent.com/55678087/246648586-57cae1bd-1d52-4730-a9e1-6d4458b39860.png)

Do not use multi gpu (mpirun).
