### ISSUE TITLE
epoch0 error

### ISSUE THREAD

**Issue by TousenKaname** [LUSSeg/PASS#8]
When the program runs to epoch0, this bug will appear in the program. I did not modify any code. Do you know anything about it

![image](https://github.com/LUSSeg/PASS/assets/55678087/d8e32eab-d4c4-4977-9ec0-b738eedf19b8)

**Comment by lzyhha** [comment]
I suggest searching for your error in Google or Baidu. 
For example, for the question you mentioned, you can get [answer1](http://www.wityx.com/post/247967_1_1.html), [answer2](https://github.com/NVIDIA/apex/pull/1282), [answer3](https://blog.csdn.net/starvapour/article/details/122275439) and so on. 

This is issue about apex. Thus you can search for "apex tuple index out of range" in your browser.

**Comment by TousenKaname** [comment]
Thanks..
